# Generated by Django 5.1.3 on 2024-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(max_length=255)),
                ("s_class", models.CharField(max_length=255)),
                ("s_addr", models.CharField(max_length=255)),
                ("s_school", models.CharField(max_length=255)),
                ("s_email", models.EmailField(max_length=255)),
            ],
        ),
    ]
