# Generated by Django 5.1.3 on 2024-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stud",
            name="s_email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
